### File name will be ".gitlab-ci.yml"

image: ubuntu:20.04

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event" #branch is not main and it is not merge request
      when: never
    - when: always

variables:  # Global variables
  image_repo: docker.io/my-docker-id/myapp
  image_version: v2.1


stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"

build_images:
  variables:  # This variables are working only on this stage
    image_repository: docker.io/my-id/myapp
    image_version: v1.1
  only:
    - main  # This argument will replace the universal Workflow rules.
  image: almalinux:9  # This argument will replace the universal Workflow rules.
  stage: build
  scripts:
    - echo "Building Docker images $image_repository"
    - echo "Tagging Docker images $image_version"

push_images:
  only:
    - main
  stage: build
  needs:
    - build_images
  scripts:
    - echo "Logging the Docker registry"
    - echo "Pushing docker images to registry"

deploy_image:
  only:
    - main
  stage: deploy
  scripts:
    - echo "Deploying Docker"
