### File name will be ".gitlab-ci.yml"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event" #branch is not main and it is not merge request
      when: never
    - when: always

variables:  # Global variables
  IMAGE_NAME: docker.io/my-docker-id/myapp
  IMAGE_TAG: v2.1
  DEV_SERVER_HOST: 172.16.4.10
  DEV_ENDPOINT: 172.16.4.10:3000


stages:
  - test
  - build

run_unit_tests:
  stage: test
  image: node:17-alpine3.14
  tags:
    - ec2
    - remote
    - docker
  before_script:
    - cd app
    - npm install



build_image:
  stage: build
  tags:
    - ec2
    - remote
    - shell
  script:
#    - docker build . -t registry.gitlab.com/nazmul/my-app:1.0
    - docker build -t $CI_REGISTRY_IMAGE/microservice/$MICRO_SERVICE:1.0


push_image:
  stage: build
  needs:
    - build_image # Depends on parameter
  tags:
    - ec2
    - remote
    - shell
  before_script:
    - echo "Loging docker registry"
#    - docker login -u nazmul -p 1234 registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    -
  script:
#    - docker push registry.gitlab.com/nazmul/my-app:1.0
    - docker push $CI_REGISTRY_IMAGE/microservice/$MICRO_SERVICE:1.0


deploy_to_dev:
  stage: deploy
  tags:
    - ec2
    - shell
    - remote
  scripts:
    - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ./docker-compose.yaml ubuntu@DEV_SERVER_HOST:/home/ubuntu
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$DEV_SERVER_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com &&
      docker-compose -f docker-compose.yaml down &&
      docker-compose -f docker-compose.yaml up -d"


environment:
  name: development
  url: $DEV_ENDPOINT