### File name will be ".gitlab-ci.yml"

stages:
  - test
  - build
  - deploy


run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"


run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"


build_images:
  stage: build
  scripts:
    - echo "Building Docker images"
    - echo "Tagging Docker images"


push_images:
  stage: build
  needs:
    - build_images
  scripts:
    - echo "Logging the Docker registry"
    - echo "Pushing docker images to registry"


deploy_image:
  stage: deploy
  scripts:
    - echo "Deploying Docker"
