### File name will be ".gitlab-ci.yml"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && CI_PIPELINE_SOURCE != "merge_request_event" #branch is not main and no merge request
      when: never
    - when: always


stages:
  - test
  - build
  - deploy

variables:
  image_repository: docker.io/my-docker-id/myapp
  image_version: v1.0

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing the data"
  scripts:
    - echo "Running tests"
  after_script:
    - echo "Cleaning up the temporary files"

build_images:
  only:
    - main
  stage: build
  scripts:
    - echo "Building Docker images"
    - echo "Tagging Docker images"

push_images:
  only:
    - main
  stage: build
  needs:
    - build_images
  scripts:
    - echo "Logging the Docker registry to $image_repository"
    - echo "Pushing docker images to registry as $image_repository:$image_version"

deploy_image:
  only:
    - main
  stage: deploy
  scripts:
    - echo "Deploying Docker"